name: ghelere-ai

services:
  app:
    container_name: rag-app
    build: 
      context: ../.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "123456"
      DB_HOST: "rag-db"	
      DB_PORT: "5432"
      DB_NAME: "postgres"
      OLLAMA_HOST: "ollama"
      OLLAMA_PORT: "11434"
    networks:
      - ai-dev-services

  db:
    container_name: rag-db
    build: 
      context: .docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - ai-dev-services
    security_opt:
      - seccomp:unconfined
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - ai-dev-services
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama:

networks:
  ai-dev-services:
    external: true