name: ghelere-ai

services:
  app:
    container_name: api-ghelere-ai
    image: ${DOCKER_USERNAME}/gh-ai-api:v5
    ports:
      - "8080:8080"
      - "2443:443"
    environment:
      - DB_VENDOR=${DB_VENDOR}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
    networks:
      - ghelere

networks:
  ghelere:
    external: true