name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/gh-ai-api:v3 .
        docker push ${{ secrets.DOCKER_USERNAME }}/gh-ai-api:v3

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/gh-ai-api:v3
          export DB_VENDOR=${{ secrets.DB_VENDOR }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_PORT=${{ secrets.DB_PORT }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export OLLAMA_HOST=${{ secrets.OLLAMA_HOST }}
          export OLLAMA_PORT=${{ secrets.OLLAMA_PORT }}
          sudo docker-compose -f docker-compose-deploy.yaml down
          sudo docker-compose -f docker-compose-deploy.yaml up -d