name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/gh-ai-api:v5 .
        docker push ${{ secrets.DOCKER_USERNAME }}/gh-ai-api:v5

    - name: Copy docker-compose file to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: 'docker-compose-deploy.yaml'
        target: '/home/ghelere/api-ghelere-ai'

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/gh-ai-api:v5
          rm -f /home/ghelere/api-ghelere-ai/.env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "DB_VENDOR=${{ secrets.DB_VENDOR }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "OLLAMA_HOST=${{ secrets.OLLAMA_HOST }}" >> /home/ghelere/api-ghelere-ai/.env
          echo "OLLAMA_PORT=${{ secrets.OLLAMA_PORT }}" >> /home/ghelere/api-ghelere-ai/.env
          cd /home/ghelere/api-ghelere-ai
          docker compose -f docker-compose-deploy.yaml down
          sleep 20
          docker compose -f docker-compose-deploy.yaml up -d